name: derpy
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    google_fonts: ^4.0.4
    intl: ^0.19.0
    supabase_flutter: ^2.4.0
    flutter_riverpod: ^2.5.1
    hooks_riverpod: ^2.5.1
    go_router: ^13.2.0
    flutter_hooks: ^0.20.5
    image_picker: ^1.0.7
    uuid: ^3.0.7
    widget_circular_animator: ^1.0.0
    google_sign_in: ^6.2.1
    date_picker_plus: ^4.0.0
    whatsapp: ^0.0.1
    url_launcher: ^6.2.6
    flutter_dotenv: ^5.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.2
    flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    ios: true
    image_path: 'assets/Derpy-logo.jpeg'
    remove_alpha_ios: true

flutter:
    uses-material-design: true

    assets:
        - assets/
        - .env
