name: derpy
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    google_fonts: ^4.0.4
    intl: ^0.19.0
    supabase_flutter: ^2.4.0
    flutter_riverpod: ^2.5.1
    hooks_riverpod: ^2.5.1
    go_router: ^13.2.0
    flutter_hooks: ^0.20.5
    image_picker: ^1.0.7
    uuid: ^3.0.7
    widget_circular_animator: ^1.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.2
    dart_code_metrics: ^5.7.6
    dart_code_metrics_presets: ^1.8.0

flutter:
    uses-material-design: true

    assets:
        - assets/
